const css = {
  root: 'dsh-modelSelect__root',
  trigger: 'dsh-modelSelect__trigger',
  triggerLabel: 'dsh-modelSelect__triggerLabel',
  triggerEffort: 'dsh-modelSelect__triggerEffort',
  chevron: 'dsh-modelSelect__chevron',
  chevronOpen: 'dsh-modelSelect__chevronOpen',
  menu: 'dsh-modelSelect__menu',
  status: 'dsh-modelSelect__status',
  empty: 'dsh-modelSelect__empty',
  error: 'dsh-modelSelect__error',
  warning: 'dsh-modelSelect__warning',
  retry: 'dsh-modelSelect__retry',
  groups: 'dsh-modelSelect__groups',
  group: 'dsh-modelSelect__group',
  groupTitle: 'dsh-modelSelect__groupTitle',
  option: 'dsh-modelSelect__option',
  selected: 'dsh-modelSelect__selected',
  optionCopy: 'dsh-modelSelect__optionCopy',
  modelName: 'dsh-modelSelect__modelName',
  description: 'dsh-modelSelect__description',
  check: 'dsh-modelSelect__check',
  cell: 'dsh-modelSelect__cell',
  cellLabel: 'dsh-modelSelect__cellLabel',
  cellValue: 'dsh-modelSelect__cellValue',
  cellChevron: 'dsh-modelSelect__cellChevron',
} as const
export default css
