const css = {
  section: 'dsh-agentPresetSection__section',
  title: 'dsh-agentPresetSection__title',
  intro: 'dsh-agentPresetSection__intro',
  group: 'dsh-agentPresetSection__group',
  groupHead: 'dsh-agentPresetSection__groupHead',
  cards: 'dsh-agentPresetSection__cards',
  card: 'dsh-agentPresetSection__card',
  cardActive: 'dsh-agentPresetSection__cardActive',
  cardBroken: 'dsh-agentPresetSection__cardBroken',
  brokenBadge: 'dsh-agentPresetSection__brokenBadge',
  cardBrokenReason: 'dsh-agentPresetSection__cardBrokenReason',
  cardMain: 'dsh-agentPresetSection__cardMain',
  cardHead: 'dsh-agentPresetSection__cardHead',
  cardName: 'dsh-agentPresetSection__cardName',
  badge: 'dsh-agentPresetSection__badge',
  inUse: 'dsh-agentPresetSection__inUse',
  cardDesc: 'dsh-agentPresetSection__cardDesc',
  cardId: 'dsh-agentPresetSection__cardId',
  cardFoot: 'dsh-agentPresetSection__cardFoot',
  iconButton: 'dsh-agentPresetSection__iconButton',
  iconDanger: 'dsh-agentPresetSection__iconDanger',
  revealedPath: 'dsh-agentPresetSection__revealedPath',
  revealedPathLabel: 'dsh-agentPresetSection__revealedPathLabel',
  secondaryButton: 'dsh-agentPresetSection__secondaryButton',
  field: 'dsh-agentPresetSection__field',
  fieldLabel: 'dsh-agentPresetSection__fieldLabel',
  input: 'dsh-agentPresetSection__input',
  dialog: 'dsh-agentPresetSection__dialog',
  dialogFields: 'dsh-agentPresetSection__dialogFields',
  viewerCode: 'dsh-agentPresetSection__viewerCode',
  error: 'dsh-agentPresetSection__error',
  deleteDialog: 'dsh-agentPresetSection__deleteDialog',
  deleteConfirm: 'dsh-agentPresetSection__deleteConfirm',
  creatorButton: 'dsh-agentPresetSection__creatorButton',
}
export default css
