const css = {
  root: 'dsh-workspaceBrowser__root',
  rail: 'dsh-workspaceBrowser__rail',
  iconButton: 'dsh-workspaceBrowser__iconButton',
  sectionHeader: 'dsh-workspaceBrowser__sectionHeader',
  sectionLabel: 'dsh-workspaceBrowser__sectionLabel',
  sectionLabelHidden: 'dsh-workspaceBrowser__sectionLabelHidden',
  searchSlot: 'dsh-workspaceBrowser__searchSlot',
  searchSlotExpanded: 'dsh-workspaceBrowser__searchSlotExpanded',
  headerActions: 'dsh-workspaceBrowser__headerActions',
  headerActionsHidden: 'dsh-workspaceBrowser__headerActionsHidden',
  search: 'dsh-workspaceBrowser__search',
  searchExpanded: 'dsh-workspaceBrowser__searchExpanded',
  searchButton: 'dsh-workspaceBrowser__searchButton',
  searchInput: 'dsh-workspaceBrowser__searchInput',
  clearButton: 'dsh-workspaceBrowser__clearButton',
  listArea: 'dsh-workspaceBrowser__listArea',
  treeBody: 'dsh-workspaceBrowser__treeBody',
  fade: 'dsh-workspaceBrowser__fade',
  wide: 'dsh-workspaceBrowser__wide',
  list: 'dsh-workspaceBrowser__list',
  flatList: 'dsh-workspaceBrowser__flatList',
  searchTree: 'dsh-workspaceBrowser__searchTree',
  groupSection: 'dsh-workspaceBrowser__groupSection',
  searchStatus: 'dsh-workspaceBrowser__searchStatus',
  searchWarning: 'dsh-workspaceBrowser__searchWarning',
  listTopDropIndicator: 'dsh-workspaceBrowser__listTopDropIndicator',
  listTopDropActive: 'dsh-workspaceBrowser__listTopDropActive',
  workspaceDropBefore: 'dsh-workspaceBrowser__workspaceDropBefore',
  workspaceDropAfter: 'dsh-workspaceBrowser__workspaceDropAfter',
  sessionOverflowButton: 'dsh-workspaceBrowser__sessionOverflowButton',
  empty: 'dsh-workspaceBrowser__empty',
  renameInput: 'dsh-workspaceBrowser__renameInput',
  renameError: 'dsh-workspaceBrowser__renameError',
  deleteAction: 'dsh-workspaceBrowser__deleteAction',
  deleteStatus: 'dsh-workspaceBrowser__deleteStatus',
}

export default css
