const css = {
  frame: 'dsh-questionComposer__frame',
  card: 'dsh-questionComposer__card',
  cardMinimized: 'dsh-questionComposer__cardMinimized',
  headerActions: 'dsh-questionComposer__headerActions',
  header: 'dsh-questionComposer__header',
  headingBlock: 'dsh-questionComposer__headingBlock',
  eyebrow: 'dsh-questionComposer__eyebrow',
  title: 'dsh-questionComposer__title',
  detail: 'dsh-questionComposer__detail',
  footerActions: 'dsh-questionComposer__footerActions',
  pager: 'dsh-questionComposer__pager',
  progress: 'dsh-questionComposer__progress',
  iconButton: 'dsh-questionComposer__iconButton',
  body: 'dsh-questionComposer__body',
  options: 'dsh-questionComposer__options',
  option: 'dsh-questionComposer__option',
  optionSelected: 'dsh-questionComposer__optionSelected',
  number: 'dsh-questionComposer__number',
  checkbox: 'dsh-questionComposer__checkbox',
  checkboxChecked: 'dsh-questionComposer__checkboxChecked',
  optionCopy: 'dsh-questionComposer__optionCopy',
  optionLine: 'dsh-questionComposer__optionLine',
  optionLabel: 'dsh-questionComposer__optionLabel',
  badge: 'dsh-questionComposer__badge',
  description: 'dsh-questionComposer__description',
  customRow: 'dsh-questionComposer__customRow',
  customRowActive: 'dsh-questionComposer__customRowActive',
  field: 'dsh-questionComposer__field',
  fieldMirror: 'dsh-questionComposer__fieldMirror',
  fieldInput: 'dsh-questionComposer__fieldInput',
  customInline: 'dsh-questionComposer__customInline',
  customBlock: 'dsh-questionComposer__customBlock',
  footer: 'dsh-questionComposer__footer',
  feedback: 'dsh-questionComposer__feedback',
}

export default css
