const css = {
  layer: 'dsh-cordisPanel__layer',
  footerButtons: 'dsh-cordisPanel__footerButtons',
  badge: 'dsh-cordisPanel__badge',
  badgeLabel: 'dsh-cordisPanel__badgeLabel',
  badgeCount: 'dsh-cordisPanel__badgeCount',
  rail: 'dsh-cordisPanel__rail',
  panel: 'dsh-cordisPanel__panel',
  header: 'dsh-cordisPanel__header',
  body: 'dsh-cordisPanel__body',
  title: 'dsh-cordisPanel__title',
  note: 'dsh-cordisPanel__note',
  readError: 'dsh-cordisPanel__readError',
  group: 'dsh-cordisPanel__group',
  rows: 'dsh-cordisPanel__rows',
  row: 'dsh-cordisPanel__row',
  rowHead: 'dsh-cordisPanel__rowHead',
  rowId: 'dsh-cordisPanel__rowId',
  rowName: 'dsh-cordisPanel__rowName',
  rowStatus: 'dsh-cordisPanel__rowStatus',
  rowDetail: 'dsh-cordisPanel__rowDetail',
  versionPicker: 'dsh-cordisPanel__versionPicker',
  rowPurpose: 'dsh-cordisPanel__rowPurpose',
  rowError: 'dsh-cordisPanel__rowError',
  rowActions: 'dsh-cordisPanel__rowActions',
  transition: 'dsh-cordisPanel__transition',
  transitionActions: 'dsh-cordisPanel__transitionActions',
  activeVersion: 'dsh-cordisPanel__activeVersion',
  actionButton: 'dsh-cordisPanel__actionButton',
  doubleCheck: 'dsh-cordisPanel__doubleCheck',
}
export default css
