const css = {
  card: 'dsh-cordisDefineRow__card',
  title: 'dsh-cordisDefineRow__title',
  row: 'dsh-cordisDefineRow__row',
  separator: 'dsh-cordisDefineRow__separator',
  name: 'dsh-cordisDefineRow__name',
  purpose: 'dsh-cordisDefineRow__purpose',
  errorSummary: 'dsh-cordisDefineRow__errorSummary',
  requestError: 'dsh-cordisDefineRow__requestError',
  readout: 'dsh-cordisDefineRow__readout',
  panelHint: 'dsh-cordisDefineRow__panelHint',
  statusLabel: 'dsh-cordisDefineRow__statusLabel',
  approvalPrompt: 'dsh-cordisDefineRow__approvalPrompt',
  notice: 'dsh-cordisDefineRow__notice',
  switch: 'dsh-cordisDefineRow__switch',
  bodyWrap: 'dsh-cordisDefineRow__bodyWrap',
  sourceCard: 'dsh-cordisDefineRow__sourceCard',
  sourceTabs: 'dsh-cordisDefineRow__sourceTabs',
  sourceTab: 'dsh-cordisDefineRow__sourceTab',
  sourceTabActive: 'dsh-cordisDefineRow__sourceTabActive',
  sourcePanel: 'dsh-cordisDefineRow__sourcePanel',
  sourceCode: 'dsh-cordisDefineRow__sourceCode',
  codeSection: 'dsh-cordisDefineRow__codeSection',
  sectionLabel: 'dsh-cordisDefineRow__sectionLabel',
  output: 'dsh-cordisDefineRow__output',
  inspectButton: 'dsh-cordisDefineRow__inspectButton',
  visuallyHidden: 'dsh-cordisDefineRow__visuallyHidden',
} as const

export default css
