const css = {
  userRow: 'dsh-messageItem__userRow',
  userStack: 'dsh-messageItem__userStack',
  bubble: 'dsh-messageItem__bubble',
  referenceSummary: 'dsh-messageItem__referenceSummary',
  contextRow: 'dsh-messageItem__contextRow',
  compactionRow: 'dsh-messageItem__compactionRow',
  compactionButton: 'dsh-messageItem__compactionButton',
  compactionLeading: 'dsh-messageItem__compactionLeading',
  compactionContextIcon: 'dsh-messageItem__compactionContextIcon',
  compactionDisclosureIcon: 'dsh-messageItem__compactionDisclosureIcon',
  compactionTitle: 'dsh-messageItem__compactionTitle',
  compactionSep: 'dsh-messageItem__compactionSep',
  compactionSummary: 'dsh-messageItem__compactionSummary',
  compactionBody: 'dsh-messageItem__compactionBody',
  retryRow: 'dsh-messageItem__retryRow',
  retrySummary: 'dsh-messageItem__retrySummary',
  retryText: 'dsh-messageItem__retryText',
  retryDetails: 'dsh-messageItem__retryDetails',
  retryDetailLabel: 'dsh-messageItem__retryDetailLabel',
  turnErrorRow: 'dsh-messageItem__turnErrorRow',
  turnErrorDot: 'dsh-messageItem__turnErrorDot',
  turnErrorCopy: 'dsh-messageItem__turnErrorCopy',
  turnErrorTitle: 'dsh-messageItem__turnErrorTitle',
  turnErrorMessage: 'dsh-messageItem__turnErrorMessage',
  turnErrorCode: 'dsh-messageItem__turnErrorCode',
  maxTokensTitle: 'dsh-messageItem__maxTokensTitle',
  refChip: 'dsh-messageItem__refChip',
  refIcon: 'dsh-messageItem__refIcon',
}
export default css
