const css = {
  root: 'dsh-conversationRoot__root',
  header: 'dsh-conversationRoot__header',
  headerHidden: 'dsh-conversationRoot__headerHidden',
  titleRow: 'dsh-conversationRoot__titleRow',
  titleCluster: 'dsh-conversationRoot__titleCluster',
  crumbs: 'dsh-conversationRoot__crumbs',
  crumbSeg: 'dsh-conversationRoot__crumbSeg',
  crumbSep: 'dsh-conversationRoot__crumbSep',
  crumb: 'dsh-conversationRoot__crumb',
  crumbSubagent: 'dsh-conversationRoot__crumbSubagent',
  crumbCurrent: 'dsh-conversationRoot__crumbCurrent',
  headerActions: 'dsh-conversationRoot__headerActions',
  headerUtilities: 'dsh-conversationRoot__headerUtilities',
  tabs: 'dsh-conversationRoot__tabs',
  tab: 'dsh-conversationRoot__tab',
  tabActive: 'dsh-conversationRoot__tabActive',
  viewArea: 'dsh-conversationRoot__viewArea',
  composerStack: 'dsh-conversationRoot__composerStack',
  composerSeat: 'dsh-conversationRoot__composerSeat',
  scrollBody: 'dsh-conversationRoot__scrollBody',
  composerHero: 'dsh-conversationRoot__composerHero',
  heroWorkspaceRow: 'dsh-conversationRoot__heroWorkspaceRow',
}
export default css
