const css = {
  root: 'dsh-inputBar__root',
  hero: 'dsh-inputBar__hero',
  notice: 'dsh-inputBar__notice',
  card: 'dsh-inputBar__card',
  cardWorkspaceTrigger: 'dsh-inputBar__cardWorkspaceTrigger',
  accessory: 'dsh-inputBar__accessory',
  overlayAnchor: 'dsh-inputBar__overlayAnchor',
  scroll: 'dsh-inputBar__scroll',
  grow: 'dsh-inputBar__grow',
  backdrop: 'dsh-inputBar__backdrop',
  backdropDisabled: 'dsh-inputBar__backdropDisabled',
  hlToken: 'dsh-inputBar__hlToken',
  hlSegment: 'dsh-inputBar__hlSegment',
  hint: 'dsh-inputBar__hint',
  pending: 'dsh-inputBar__pending',
  input: 'dsh-inputBar__input',
  mirror: 'dsh-inputBar__mirror',
  row: 'dsh-inputBar__row',
  tools: 'dsh-inputBar__tools',
  modes: 'dsh-inputBar__modes',
  trailing: 'dsh-inputBar__trailing',
  add: 'dsh-inputBar__add',
  select: 'dsh-inputBar__select',
  primary: 'dsh-inputBar__primary',
  retry: 'dsh-inputBar__retry',
  textRef: 'dsh-inputBar__textRef',
  textRefTrigger: 'dsh-inputBar__textRefTrigger',
  textRefTriggerGlyph: 'dsh-inputBar__textRefTriggerGlyph',
  textRefIcon: 'dsh-inputBar__textRefIcon',
  chip: 'dsh-inputBar__chip',
  chipTrigger: 'dsh-inputBar__chipTrigger',
  chipTriggerGlyph: 'dsh-inputBar__chipTriggerGlyph',
  chipIcon: 'dsh-inputBar__chipIcon',
  chipInvalid: 'dsh-inputBar__chipInvalid',
}

export default css
