const css = {
  root: 'dsh-toolRow__root',
  row: 'dsh-toolRow__row',
  leading: 'dsh-toolRow__leading',
  chevron: 'dsh-toolRow__chevron',
  title: 'dsh-toolRow__title',
  sep: 'dsh-toolRow__sep',
  summary: 'dsh-toolRow__summary',
  summarySuffix: 'dsh-toolRow__summarySuffix',
  fileLink: 'dsh-toolRow__fileLink',
  errorSummary: 'dsh-toolRow__errorSummary',
  bodyWrap: 'dsh-toolRow__bodyWrap',
  inspectButton: 'dsh-toolRow__inspectButton',
  bodyScroll: 'dsh-toolRow__bodyScroll',
  ioCard: 'dsh-toolRow__ioCard',
  ioSection: 'dsh-toolRow__ioSection',
  ioLabel: 'dsh-toolRow__ioLabel',
  ioDivider: 'dsh-toolRow__ioDivider',
  ioText: 'dsh-toolRow__ioText',
  codeBody: 'dsh-toolRow__codeBody',
  terminalBody: 'dsh-toolRow__terminalBody',
  diffBody: 'dsh-toolRow__diffBody',
  readBody: 'dsh-toolRow__readBody',
  searchBody: 'dsh-toolRow__searchBody',
  webBody: 'dsh-toolRow__webBody',
  searchRecovery: 'dsh-toolRow__searchRecovery',
  visuallyHidden: 'dsh-toolRow__visuallyHidden',
}
export default css
