const css = {
  projectRow: 'dsh-rows__projectRow',
  sessionRow: 'dsh-rows__sessionRow',
  selected: 'dsh-rows__selected',
  searchResultRow: 'dsh-rows__searchResultRow',
  searchResultHeading: 'dsh-rows__searchResultHeading',
  searchResultTitle: 'dsh-rows__searchResultTitle',
  searchResultMeta: 'dsh-rows__searchResultMeta',
  searchResultWorkspace: 'dsh-rows__searchResultWorkspace',
  searchResultSnippet: 'dsh-rows__searchResultSnippet',
  rowActions: 'dsh-rows__rowActions',
  title: 'dsh-rows__title',
  flatSessionRowWithoutStatus: 'dsh-rows__flatSessionRowWithoutStatus',
  slot: 'dsh-rows__slot',
  visuallyHidden: 'dsh-rows__visuallyHidden',
  folderActive: 'dsh-rows__folderActive',
  chevron: 'dsh-rows__chevron',
  folder: 'dsh-rows__folder',
  arrow: 'dsh-rows__arrow',
  arrowOpen: 'dsh-rows__arrowOpen',
  projectText: 'dsh-rows__projectText',
  renameInput: 'dsh-rows__renameInput',
  meta: 'dsh-rows__meta',
  time: 'dsh-rows__time',
  dot: 'dsh-rows__dot',
  menuOpen: 'dsh-rows__menuOpen',
  dropBefore: 'dsh-rows__dropBefore',
  dropAfter: 'dsh-rows__dropAfter',
  hoverContent: 'dsh-rows__hoverContent',
  hoverTitle: 'dsh-rows__hoverTitle',
  hoverPath: 'dsh-rows__hoverPath',
  hoverTime: 'dsh-rows__hoverTime',
  hoverStatus: 'dsh-rows__hoverStatus',
  iconButton: 'dsh-rows__iconButton',
} as const
export default css
