const css = {
  root: 'dsh-subagentHeaderLineage__root',
  switcherRoot: 'dsh-subagentHeaderLineage__switcherRoot',
  trigger: 'dsh-subagentHeaderLineage__trigger',
  switcherTrigger: 'dsh-subagentHeaderLineage__switcherTrigger',
  ancestorSwitcherTrigger: 'dsh-subagentHeaderLineage__ancestorSwitcherTrigger',
  switcherTitle: 'dsh-subagentHeaderLineage__switcherTitle',
  separator: 'dsh-subagentHeaderLineage__separator',
  activitySlot: 'dsh-subagentHeaderLineage__activitySlot',
  triggerOpen: 'dsh-subagentHeaderLineage__triggerOpen',
  menu: 'dsh-subagentHeaderLineage__menu',
  node: 'dsh-subagentHeaderLineage__node',
  row: 'dsh-subagentHeaderLineage__row',
  clickarea: 'dsh-subagentHeaderLineage__clickarea',
  disabled: 'dsh-subagentHeaderLineage__disabled',
  loadingRow: 'dsh-subagentHeaderLineage__loadingRow',
  disclosure: 'dsh-subagentHeaderLineage__disclosure',
  disclosureSpace: 'dsh-subagentHeaderLineage__disclosureSpace',
  disclosureOpen: 'dsh-subagentHeaderLineage__disclosureOpen',
  content: 'dsh-subagentHeaderLineage__content',
  label: 'dsh-subagentHeaderLineage__label',
  summary: 'dsh-subagentHeaderLineage__summary',
  currentLabel: 'dsh-subagentHeaderLineage__currentLabel',
  metrics: 'dsh-subagentHeaderLineage__metrics',
  metricToken: 'dsh-subagentHeaderLineage__metricToken',
  metricDuration: 'dsh-subagentHeaderLineage__metricDuration',
  children: 'dsh-subagentHeaderLineage__children',
  notice: 'dsh-subagentHeaderLineage__notice',
  error: 'dsh-subagentHeaderLineage__error',
  refresh: 'dsh-subagentHeaderLineage__refresh',
} as const
export default css
