/**
 * Cordis-free React primitives styled only through `--dsw-*` tokens.
 */

export { StateDot } from './StateDot.tsx'
export type { StateDotState } from './StateDot.tsx'
export { DisclosureRow } from './DisclosureRow.tsx'
export type { DisclosureRowProps } from './DisclosureRow.tsx'
export { Button } from './Button.tsx'
export type { ButtonVariant } from './Button.tsx'
export { Pill } from './Pill.tsx'
export { Input } from './Input.tsx'
export { Menu, DshMenu, renderMenu } from './Menu.tsx'
export type { MenuEntry, MenuItem, MenuSeparator, MenuLabel, MenuProps } from './Menu.tsx'
export { createAnchoredMaxHeight } from './useAnchoredMaxHeight.ts'
export type { AnchoredMaxHeightOptions, AnchoredMaxHeightController } from './useAnchoredMaxHeight.ts'
export { createAnchoredPosition } from './useAnchoredPosition.ts'
export type { AnchoredPositionOptions, AnchoredPosition, AnchoredPositionController } from './useAnchoredPosition.ts'
export { createDismissOnOutsidePointer } from './useDismissOnOutsidePointer.ts'
export type { DismissOnOutsidePointerOptions, DismissOnOutsidePointerController } from './useDismissOnOutsidePointer.ts'
export { createCopyFeedback } from './use-copy-feedback.ts'
export type { CopyFeedbackController } from './use-copy-feedback.ts'
export { HoverCard, DshHoverCard, renderHoverCard } from './HoverCard.tsx'
export type { HoverCardProps } from './HoverCard.tsx'
export { Modal, DshModal, renderModal } from './Modal.tsx'
export type { ModalProps } from './Modal.tsx'
export { OnboardingSurface, DshOnboardingSurface } from './OnboardingSurface.tsx'
export type { OnboardingSurfaceProps } from './OnboardingSurface.tsx'
export { RiskConfirmation } from './RiskConfirmation.tsx'
export type { RiskConfirmationProps } from './RiskConfirmation.tsx'
export { ConnectionBanner } from './ConnectionBanner.tsx'
export { FishLogo } from './FishLogo.tsx'
export { BrandWordmark } from './BrandWordmark.tsx'
export type { BrandWordmarkProps } from './BrandWordmark.tsx'
export { Tooltip, DshTooltip, renderTooltip } from './Tooltip.tsx'
export type { TooltipSide, TooltipProps } from './Tooltip.tsx'
export { DshToast, mountToast } from './Toast.tsx'
export type { ToastProps } from './Toast.tsx'
export { writeClipboard } from './clipboard.ts'
export { JsonTree, DshJsonTree, renderJsonTree } from './JsonTree.tsx'
export type { JsonTreeProps, JsonTreeLabels } from './JsonTree.tsx'
export { TerminalBlock, DshTerminalBlock, renderTerminalBlock, DEFAULT_TERMINAL_MAX_LINES } from './TerminalBlock.tsx'
export type { TerminalBlockProps, TerminalBlockLabels } from './TerminalBlock.tsx'
export { ReadBlock, DEFAULT_READ_MAX_LINES } from './ReadBlock.tsx'
export type { ReadBlockProps, ReadBlockLine } from './ReadBlock.tsx'
export { DiffBlock, DEFAULT_DIFF_MAX_LINES } from './DiffBlock.tsx'
export type { DiffBlockProps, DiffHunk } from './DiffBlock.tsx'
export { SearchBlock, DshSearchBlock, renderSearchBlock, DEFAULT_SEARCH_MAX_LINES } from './SearchBlock.tsx'
export type {
  SearchBlockProps, SearchMatchesBlockProps, SearchPathsBlockProps, SearchFileGroup, SearchBlockLineMatch,
} from './SearchBlock.tsx'
export { WebBlock } from './WebBlock.tsx'
export type { WebBlockProps, WebSearchBlockProps, WebFetchBlockProps, WebSourceView } from './WebBlock.tsx'
export { CodeBlock, DshCodeBlock, renderCodeBlock } from './markdown/CodeBlock.tsx'
export type { CodeBlockProps } from './markdown/CodeBlock.tsx'
export { JsonBlock, DshJsonBlock, renderJsonBlock } from './markdown/JsonBlock.tsx'
export type { JsonBlockProps } from './markdown/JsonBlock.tsx'
export { MarkdownText, DshMarkdownText, renderMarkdownText } from './markdown/MarkdownText.tsx'
export type { MarkdownCodeLabels, MarkdownFileMentions, MarkdownTextProps } from './markdown/MarkdownText.tsx'
export { MessageText } from './markdown/MessageText.tsx'
export { extractMarkdownPlainText } from './markdown/plain-text.ts'
export type { MarkdownPlainTextMode, MarkdownPlainTextOptions } from './markdown/plain-text.ts'
export * from './icons/index.tsx'
